const fs=require('fs'),assert=require('node:assert/strict');
const c=JSON.parse(fs.readFileSync('assets/data/atlas-catalogue.json')),g=JSON.parse(fs.readFileSync('assets/data/atlas-galaxy.json')),art=JSON.parse(fs.readFileSync('assets/data/atlas-art.json')).planets;
const math=require('../assets/js/atlas-space.js');
assert.equal(c.planets.length,40);assert.equal(new Set(c.planets.map(p=>p.id)).size,40);
const forbidden=/posterBrief|landscapeBrief|"prompt"|Use blended boundaries|Keep the famous|main copy|before publication|must not imply|needs an agreed rule/i;
assert(!forbidden.test(JSON.stringify(c)),'Editorial instructions in public catalogue');
for(const p of c.planets){assert(p.story?.length,p.id+' needs a story');assert(p.layers?.length>=3,p.id+' needs layers');assert(g.hosts[p.host],p.id+' needs coordinates');const d=c.systems[p.host].orbits.find(d=>d.name===p.archiveName);assert(d,p.id+' missing from its own system');assert.equal(p.a,d.a);assert.equal(p.year,d.period);for(const l of p.layers){assert(l.text.length>40);assert(l.source.title);assert(l.source.url.startsWith('https://'));}for(const s of p.story){assert(s.text.length>100);assert(s.url.startsWith('https://'));}for(const k of ['texture','landscape','poster','posterDownload'])assert(fs.existsSync('blog/'+art[p.id][k]),p.id+' missing '+k);}
for(const s of Object.values(c.systems)){assert.equal(s.omitted.length,0);for(const d of s.orbits){assert(d.a>0&&d.period>0&&d.eccentricity>=0&&d.eccentricity<1);for(let i=0;i<16;i++){const t=d.period*i/16,[x,y]=math.position(d,t);assert(Number.isFinite(x)&&Number.isFinite(y));const ellipse=((x+d.a*d.eccentricity)/d.a)**2+(y/(d.a*Math.sqrt(1-d.eccentricity**2)))**2;assert(Math.abs(ellipse-1)<1e-10);const after=math.position(d,t+d.period);assert(Math.hypot(x-after[0],y-after[1])<1e-8);}const per=math.position(d,0),apo=math.position(d,d.period/2);assert(Math.abs(Math.hypot(...per)-d.a*(1-d.eccentricity))<1e-8);assert(Math.abs(Math.hypot(...apo)-d.a*(1+d.eccentricity))<1e-8);}}
assert.deepEqual(math.galactic(0,0,0),[8178,0,0]);assert.equal(math.galactic(0,0,100)[0],8078);assert(Math.abs(math.galactic(90,0,100)[1]-100)<1e-8);
for(const h of Object.values(g.hosts)){const [x,y,z]=math.galactic(h.longitude,h.latitude,h.distance);assert(Math.abs(Math.hypot(x-8178,y,z)-h.distance)<1e-8);}
console.log('PASS: 40 records, artwork, citations, layered interiors, 86 orbital paths, periods, and 37 coordinate distances.');
